In [2]:
import pandas as pd

c:\Users\A-C19\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
df = pd.read_csv('balance.txt', delim_whitespace=True)

df.head()

C:\Users\A-C19\AppData\Local\Temp\ipykernel_11476\1120221762.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv('balance.txt', delim_whitespace=True)

,Balance,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity
0,12.240798,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian
1,23.283334,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian
2,22.530409,104.593,7075,514,4,71,11,Male,No,No,Asian
3,27.652811,148.924,9504,681,3,36,11,Female,No,No,Asian
4,16.893978,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian

In [4]:
# Compare the average income based on ethnicity.
print(f"The average income based on ethnicity is: {df.groupby('Ethnicity')['Income'].mean()}")

The average income based on ethnicity is: Ethnicity
African American    47.682101
Asian               44.187833
Caucasian           44.521945
Name: Income, dtype: float64

In [5]:
# On average, do married or single people have a higher balance?
# Group by Married to show results based on the result of this coumn
# Showing the mean of the balance per catogory
print(df.groupby('Married')['Balance'].mean())

Married
No     13.493509
Yes    13.388473
Name: Balance, dtype: float64

In [6]:
# What is the highest income in our dataset?
print("The highest income in our dataset is", df.loc[:, "Income"].max())

The highest income in our dataset is 186.634

In [7]:
# What is the lowest income in our dataset?
print("The lowest income in our dataset is", df.loc[:, "Income"].min())

The lowest income in our dataset is 10.354

In [8]:
# How many cards do we have recorded in our dataset? (Hint: use `sum()`)
cards_ttl = df.loc[:,"Cards"].sum()
print(f"We have a total of {cards_ttl} cards within our data set")

We have a total of 1183 cards within our data set

In [9]:
# How many females do we have information for vs how many males? 
# (Hint: use `count()` for a list of all methods for computation of descriptive stats, explore the 
# [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#computations-descriptive-stats)).

female_count = df["Gender"].value_counts()["Female"]
male_count = df["Gender"].value_counts()["Male"]

print(f"We have {female_count} Females within this data compared to {male_count} Males")

We have 207 Females within this data compared to 193 Males